# Generated by Django 5.1.6 on 2025-02-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('prestador', 'Prestador de Servicio')], default='cliente', max_length=10),
        ),
    ]
