# Generated by Django 5.1.6 on 2025-02-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
